/**
 * 
 */
package com.gateway.traineeproject.model;

/**
 * @author Hiren Khatri
 *Response class for getToken Request
 *It contains the token generated by the JWT
 */
public class JwtResponse {
	String token;
	
	public JwtResponse() {
		
	}

	/**
	 * @param token
	 */
	public JwtResponse(String token) {
		super();
		this.token = token;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}
	
	
}
